### ISSUE TITLE
Oh nooooo

### ISSUE THREAD

**Issue by someJOJOreference** [HiroShihiko/mindustrys-bizarre-adventure#2]
Meteorites and arrows cannot be placed in the core. Obviously the work of the enemy stand.

**Comment by HiroShihiko** [comment]
That's not a problem, meteorites aren't supposed to be inputted in the core, and you're probably putting arrow heads and handles into the core and not the actual arrow and requiem arrow.

**Comment by HiroShihiko** [comment]
> Meteorites and arrows cannot be placed in the core. Obviously the work of the enemy stand.

That's not a problem, meteorites aren't supposed to be inputted in the core, and you're probably putting arrow heads and handles into the core and not the actual arrow and requiem arrow.

**Comment by someJOJOreference** [comment]
But in order to unlock useable arrow constructor you need meteorites🤔

![Uploading 851AE902-7464-4E25-BA1E-226BFDAEFB2D.png…]()
