### ISSUE TITLE
> Meteorites and arrows cannot be placed in the core. Obviously the work of the enemy stand.

### ISSUE THREAD

**Issue by someJOJOreference** [HiroShihiko/mindustrys-bizarre-adventure#5]
> Meteorites and arrows cannot be placed in the core. Obviously the work of the enemy stand.

> That's not a problem, meteorites aren't supposed to be inputted in the core, and you're probably putting arrow heads and handles into the core and not the actual arrow and requiem arrow.

But in order to unlock usable arrow constructor you need meteorites🤔

![image](https://user-images.githubusercontent.com/57332616/86021096-63dfda00-ba31-11ea-8b2a-4d7906629c94.png)
And here i have some complete arrows not going in
![image](https://user-images.githubusercontent.com/57332616/86024467-b15e4600-ba35-11ea-97ac-8d645d3184a2.png)

**Comment by HiroShihiko** [comment]
> > Meteorites and arrows cannot be placed in the core. Obviously the work of the enemy stand.
> 
> > That's not a problem, meteorites aren't supposed to be inputted in the core, and you're probably putting arrow heads and handles into the core and not the actual arrow and requiem arrow.
> 
> But in order to unlock usable arrow constructor you need meteorites
> 
> ![image](https://user-images.githubusercontent.com/57332616/86021096-63dfda00-ba31-11ea-8b2a-4d7906629c94.png)
> And here i have some complete arrows not going in
> ![image](https://user-images.githubusercontent.com/57332616/86024467-b15e4600-ba35-11ea-97ac-8d645d3184a2.png)

okay, we're working on it now

**Comment by HiroShihiko** [comment]
> > Meteorites and arrows cannot be placed in the core. Obviously the work of the enemy stand.
> 
> > That's not a problem, meteorites aren't supposed to be inputted in the core, and you're probably putting arrow heads and handles into the core and not the actual arrow and requiem arrow.
> 
> But in order to unlock usable arrow constructor you need meteorites
> 
> ![image](https://user-images.githubusercontent.com/57332616/86021096-63dfda00-ba31-11ea-8b2a-4d7906629c94.png)
> And here i have some complete arrows not going in
> ![image](https://user-images.githubusercontent.com/57332616/86024467-b15e4600-ba35-11ea-97ac-8d645d3184a2.png)

i think i see the problem, you see...those sprites and coding aren't in our mod...you must have inputted the old mod which had bad spriting (hence the ugly looking meteorite compressor)

**Comment by someJOJOreference** [comment]
> i think i see the problem, you see...those sprites and coding aren't in our mod...you must have inputted the old mod which had bad spriting (hence the ugly looking meteorite compressor)

Yeah, all working now, thanks. Great mod btw, keep it up.
